# Generated by Django 4.2.1 on 2023-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_reg', '0002_alter_apple_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='year_of_production',
            field=models.IntegerField(),
        ),
    ]
