# Generated by Django 4.2.1 on 2023-06-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_reg', '0003_alter_apple_year_of_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apple',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='apple',
            name='long',
        ),
        migrations.AddField(
            model_name='apple',
            name='geolocation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
