# Generated by Django 4.2.1 on 2023-06-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
    ]
